export const SET_NOWPLAYING = 'SET_NOWPLAYING';
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';
export const REMOVE_CURRENT_MOVIE = 'REMOVE_CURRENT_MOVIE';
export const SET_DISCOVER_MOVIES = 'SET_DISCOVER_MOVIES';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const REMOVE_SEARCH_RESULTS = 'REMOVE_SEARCH_RESULTS';

export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const SET_USER = 'SET_USER';
export const SET_ALERT = 'SET_ALERT';
export const ADD_MOVIE_TO_WATCHLIST = 'ADD_MOVIE_TO_WATCHLIST';
export const REMOVE_MOVIE_FROM_WATCHLIST = 'REMOVE_MOVIE_FROM_WATCHLIST';
export const ADD_TV_TO_WATCHLIST = 'ADD_TV_TO_WATCHLIST';
export const REMOVE_TV_FROM_WATCHLIST = 'REMOVE_TV_FROM_WATCHLIST';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_LISTS = 'SET_LISTS';
export const SET_WATCHLISTS = 'SET_WATCHLISTS';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SET_CURRENT_PERSON = 'SET_CURRENT_PERSON';

export const SET_CURRENT_TV = 'SET_CURRENT_TV';
export const SET_DISCOVER_TV = 'SET_DISCOVER_TV';
