export const SET_NOWPLAYING = 'SET_NOWPLAYING'
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE'
export const REMOVE_CURRENT_MOVIE = 'REMOVE_CURRENT_MOVIE'


export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const REMOVE_SEARCH_RESULTS = 'REMOVE_SEARCH_RESULTS'


export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'


export const SET_CURRENT_PERSON = 'SET_CURRENT_PERSON'

export const SET_CURRENT_TV = 'SET_CURRENT_TV'

